// Congress identifiers shared by the P2.1 adapters (docs/design/P2.1.md §1.4, §3.0, §3.1): the pinned current
// session, the year -> Congress/session rule, and the CLOSED bill-type tables (anything outside them = drift, except a
// floor href segment, which only loses its related key). Builders do not edit this file (§6); changes go to the
// integrator.

/**
 * The session the index URLs are built from (DESIGN §3.0, R-15). Pinned on purpose: the rollover to 120-1 (Jan 3 2027)
 * is a code change plus fixtures that cannot exist before that day, listed on the P2.2 go-live checklist. There is NO
 * wall-clock test for it (a dated test would hold CI red from mid-December).
 */
export const CURRENT: Readonly<{ congress: number; session: 1 | 2; year: number }> = Object.freeze({ congress: 119, session: 2, year: 2026 })

/** 1 -> `1st`, 2 -> `2nd` (the House listing's `Session=` query value). */
export function sessionOrdinal(n: 1 | 2): '1st' | '2nd' {
  return n === 1 ? '1st' : '2nd'
}

/** `1st` -> 1, `2nd` -> 2 (House `<session>`); anything else null (a 3rd session is adapter drift). */
export function sessionNumber(s: string): 1 | 2 | null {
  const t = s.trim()
  return t === '1st' ? 1 : t === '2nd' ? 2 : null
}

/**
 * The §3.1 year rule: congress = floor((Y - 1787) / 2), session 1 in an odd year, 2 in an even year (2025 = 119/1,
 * 2026 = 119/2). Used by house.clerk.votes (URL year vs XML identity) and house.clerk.floor (vote links' `year=`, the
 * day file's single Congress). A session runs from Jan 1 of its year to noon Eastern on Jan 3 of the next (20th
 * Amendment): senate vote_116_2_00292 (congress_year 2020) is dated January 1, 2021, so the adapters bound a vote's date
 * by its session, not by this rule's year (review 483d7ab time F3). null for a year outside 1789..2200 or not an integer.
 */
export function congressSessionOfYear(y: number): { congress: number; session: 1 | 2 } | null {
  if (!Number.isInteger(y) || y < 1789 || y > 2200) return null
  return { congress: Math.floor((y - 1787) / 2), session: y % 2 === 1 ? 1 : 2 }
}

/** Our bill-type slugs (bill:{congress}:{type}:{n}, DESIGN §1.4). */
export type BillType = 'hr' | 'hres' | 'hjres' | 'hconres' | 's' | 'sres' | 'sjres' | 'sconres'

/** How a bill number is printed in our titles: `H.R. 5334`, `S.J.Res. 31`. */
export const BILL_LABEL: Readonly<Record<BillType, string>> = {
  hr: 'H.R.', hres: 'H.Res.', hjres: 'H.J.Res.', hconres: 'H.Con.Res.', s: 'S.', sres: 'S.Res.', sjres: 'S.J.Res.', sconres: 'S.Con.Res.',
}

/** House `<legis-num>` type tokens (closed). */
export const HOUSE_LEGIS_TYPES: Readonly<Record<string, BillType>> = {
  'H R': 'hr', 'H RES': 'hres', 'H J RES': 'hjres', 'H CON RES': 'hconres', S: 's', 'S RES': 'sres', 'S J RES': 'sjres', 'S CON RES': 'sconres',
}

/** House `<legis-num>` values that are not bills (closed). */
export const HOUSE_NON_BILL = { QUORUM: 'quorum', ADJOURN: 'adjourn' } as const

export type LegisNum =
  | { kind: 'bill'; type: BillType; number: number }
  | { kind: 'quorum' | 'adjourn' }

/**
 * Parse a House `<legis-num>` ("H R 5334", "S J RES 31", "QUORUM", "ADJOURN"; whitespace collapsed first). null =
 * outside the closed table, which the House vote adapter reports as drift. An absent legis-num (a Speaker election) is
 * the caller's case, not this function's.
 */
export function parseLegisNum(text: string): LegisNum | null {
  const t = text.replace(/\s+/g, ' ').trim()
  if (t === 'QUORUM') return { kind: 'quorum' }
  if (t === 'ADJOURN') return { kind: 'adjourn' }
  const m = /^([A-Z]+(?: [A-Z]+)*) ([1-9][0-9]{0,5})$/.exec(t)
  if (!m) return null
  const type = HOUSE_LEGIS_TYPES[m[1]!]
  return type ? { kind: 'bill', type, number: Number(m[2]) } : null
}

/** Senate `<document_type>` values (closed; scout list, `H.Con.Res.` seen only in the menu). */
export const SENATE_DOCUMENT_TYPES: Readonly<Record<string, BillType | 'nomination' | 'amendment'>> = {
  'H.R.': 'hr', 'S.': 's', 'S.Res.': 'sres', 'S.J.Res.': 'sjres', 'H.J.Res.': 'hjres', 'S.Con.Res.': 'sconres',
  'H.Res.': 'hres', 'H.Con.Res.': 'hconres', PN: 'nomination', 'S.Amdt.': 'amendment',
}

/** Senate document_type -> our kind; null = outside the closed table (drift). */
export function senateDocumentType(t: string): BillType | 'nomination' | 'amendment' | null {
  return Object.hasOwn(SENATE_DOCUMENT_TYPES, t.trim()) ? SENATE_DOCUMENT_TYPES[t.trim()]! : null
}

/** House floor `<a rel="bill">` href path segments (DESIGN §3.0; the two Senate resolution kinds by symmetry). An unknown
 * segment only means no related key, never drift. */
export const FLOOR_BILL_SEGMENTS: Readonly<Record<string, BillType>> = {
  'house-bill': 'hr', 'house-resolution': 'hres', 'house-joint-resolution': 'hjres', 'house-concurrent-resolution': 'hconres',
  'senate-bill': 's', 'senate-resolution': 'sres', 'senate-joint-resolution': 'sjres', 'senate-concurrent-resolution': 'sconres',
}

export function floorBillType(segment: string): BillType | null {
  return Object.hasOwn(FLOOR_BILL_SEGMENTS, segment) ? FLOOR_BILL_SEGMENTS[segment]! : null
}

/** `H.R. 5334` (our title wording for a bill: an identifier we format, never the bill's title). */
export function fmtBill(type: BillType, n: number): string {
  return `${BILL_LABEL[type]} ${n}`
}

/** `bill:119:hr:5334` (thread_key / related key). */
export function billKey(congress: number, type: BillType, n: number): string {
  return `bill:${congress}:${type}:${n}`
}

/**
 * `nomination:119:PN1129`, `nomination:119:PN730-11`: the PN number with its partition suffix as printed (DESIGN
 * §1.4). `partition` is the separately printed part (senate.schedule `Documents`): "0", "0 " or empty = none.
 * null when the number is not `\d+` or `\d+-\d+`.
 */
export function nominationKey(congress: number, number: string, partition?: string | null): string | null {
  const n = number.trim()
  const p = (partition ?? '').trim()
  if (!/^[1-9][0-9]*(-[1-9][0-9]*)?$/.test(n)) return null
  if (p === '' || p === '0') return `nomination:${congress}:PN${n}`
  if (n.includes('-') || !/^[1-9][0-9]*$/.test(p)) return null
  return `nomination:${congress}:PN${n}-${Number(p)}`
}
