// Members support module (docs/design/P2.1.md §2.2, §2.3, §3.6): a build-time generated map of Members of Congress
// (bioguide -> display name [+ district], Senate LIS id -> bioguide), imported as plain data by the vote adapters.
// Not a SourceDefinition and never in a source list; reachable only through `@ced/adapters/fixture-only` (D-058).
//
// The map is regenerated by a vitest case, never by a script (Node cannot import the repo's .js-suffixed TS modules):
//   UPDATE_MEMBERS=1 npx vitest run packages/adapters/test/members.test.ts
// Without the flag the same case asserts the committed map equals the rebuild, so a hand edit fails the gate.
//
// Rules this file enforces:
// - fail closed: a bad upstream answer returns { ok: false } and the committed map is left as is;
// - append-only within a Congress: every id in the previous map for the same Congress stays (a re-ingested older vote
//   keeps resolving after a member leaves the current roster), a changed display name takes the new name;
// - party and state are never read (the vote XML prints them as of the vote; the 2026-09-02 snapshot has a party
//   defect, members scout), and names are never joined on (`Graham (R-SC)` is two different senators).
import { sha256Hex } from '@ced/schema'
import type { FetchedResponse } from '../types.js'
import generated from '../generated/members.json' with { type: 'json' }

/** The fields of a congress-legislators record this module reads (legislators-current/-historical.json). */
export interface LegislatorRecord {
  id: { bioguide: string; lis?: string }
  name: { first?: string; middle?: string; nickname?: string; last: string; suffix?: string; official_full?: string }
  terms: Array<{ type: 'rep' | 'sen'; start: string; end: string; state: string; district?: number }>
}

/** The committed extract of departed members (generated/members_departed_119.json). */
export interface DepartedSeed {
  url: string
  sha256: string
  fetched_at: string
  /** The Congress the seed belongs to and the date its first term began (members whose last term ends after it). */
  congress: number
  congress_start: string
  count: number
  members: LegislatorRecord[]
}

export interface MembersMap {
  /** The Congress this map is append-only within (a new Congress starts from the current roster alone). */
  congress: number
  source: {
    url: string
    sha256: string
    last_modified: string | null
    built_at: string
    departed_seed: { url: string; sha256: string; fetched_at: string; count: number }
  }
  /** Ids kept only because the previous map had them (left the roster during this Congress after the seed was cut). */
  kept_from_previous: string[]
  /** bioguide -> [displayName] for senators, [displayName, district] for representatives and delegates (0 = at-large). */
  members: Record<string, [string] | [string, number]>
  /** Senate LIS member id -> bioguide. */
  lis: Record<string, string>
}

export type BuildResult = { ok: true; map: MembersMap } | { ok: false; error: string }

export const MEMBERS_URL = 'https://unitedstates.github.io/congress-legislators/legislators-current.json'
export const HISTORICAL_URL = 'https://unitedstates.github.io/congress-legislators/legislators-historical.json'
/** Accepted record count of legislators-current.json (539 on 2026-10-02). */
export const CURRENT_COUNT_RANGE = [530, 545] as const
export const SENATORS_RANGE = [95, 100] as const
const BIOGUIDE = /^[A-Z]\d{6}$/
const LIS = /^S\d{3}$/

/** `official_full ?? [nickname ?? first, last, suffix].join(' ')` (W000832 has no official_full). */
export function displayName(n: LegislatorRecord['name']): string {
  if (typeof n.official_full === 'string' && n.official_full.trim() !== '') return n.official_full.trim()
  return [n.nickname ?? n.first, n.last, n.suffix].filter((x): x is string => typeof x === 'string' && x.trim() !== '').map((x) => x.trim()).join(' ')
}

/** One record's structural checks; returns the problem or null. */
function recordProblem(r: unknown, where: string): string | null {
  const x = r as Partial<LegislatorRecord> | null
  const bg = x?.id?.bioguide
  if (typeof bg !== 'string' || !BIOGUIDE.test(bg)) return `${where}: bioguide ${JSON.stringify(bg)} is not [A-Z] + 6 digits`
  const last = Array.isArray(x!.terms) ? x!.terms[x!.terms.length - 1] : undefined
  if (!last || (last.type !== 'sen' && last.type !== 'rep')) return `${where} ${bg}: no last term of type sen/rep`
  const lis = x!.id!.lis
  if (last.type === 'sen' && (typeof lis !== 'string' || !LIS.test(lis))) return `${where} ${bg}: a senator without an S### lis id`
  if (last.type === 'rep' && lis !== undefined) return `${where} ${bg}: a representative with a lis id (${lis})`
  if (last.type === 'rep' && !(Number.isInteger(last.district) && (last.district as number) >= 0)) return `${where} ${bg}: a representative without a district`
  if (!x!.name || typeof x!.name.last !== 'string' || displayName(x!.name) === '') return `${where} ${bg}: no usable name`
  return null
}

function sortedRecord<V>(m: Map<string, V>): Record<string, V> {
  const out: Record<string, V> = {}
  for (const k of [...m.keys()].sort()) out[k] = m.get(k)!
  return out
}

/**
 * Pure. `current` is the legislators-current.json response; `departed` the committed departed-member seed; `previous`
 * the committed map (null on a first build). Fails closed on: non-200 (a 304 is never an empty roster), an empty body,
 * a content-type that is not JSON (except raw.githubusercontent.com's `text/plain`), a body that is not a JSON array,
 * a record count outside 530-545, senators outside 95-100, a senator without an S### lis or a representative with one,
 * a duplicate bioguide or lis, a malformed bioguide, a lis that changed owner since `previous`.
 */
export function buildMembersMap(
  current: FetchedResponse,
  departed: DepartedSeed,
  previous: MembersMap | null,
  opts: { builtAt: string },
): BuildResult {
  const fail = (error: string): BuildResult => ({ ok: false, error })
  if (current.status !== 200) return fail(`HTTP ${current.status}: not a fresh roster (a 304 is never an empty one)`)
  if (current.body.length === 0) return fail('empty body')
  const ct = (current.headers['content-type'] ?? '').toLowerCase()
  let host = ''
  try {
    host = new URL(current.url).host
  } catch {
    return fail(`bad url ${current.url}`)
  }
  const rawPlain = host === 'raw.githubusercontent.com' && ct.startsWith('text/plain')
  if (!ct.includes('json') && !rawPlain) return fail(`content-type "${ct}" is not JSON`)
  let rows: unknown
  try {
    rows = JSON.parse(current.body)
  } catch {
    return fail('body is not JSON')
  }
  if (!Array.isArray(rows)) return fail('body is not a JSON array')
  if (rows.length < CURRENT_COUNT_RANGE[0] || rows.length > CURRENT_COUNT_RANGE[1]) {
    return fail(`${rows.length} records, outside ${CURRENT_COUNT_RANGE.join('-')}`)
  }
  if (!departed || !Array.isArray(departed.members) || departed.members.length !== departed.count) {
    return fail('departed seed: count does not match its members')
  }

  const members = new Map<string, [string] | [string, number]>()
  const lis = new Map<string, string>()
  let senators = 0
  const add = (r: LegislatorRecord, where: string, skipKnown: boolean): string | null => {
    const p = recordProblem(r, where)
    if (p) return p
    const bg = r.id.bioguide
    if (members.has(bg)) return skipKnown ? null : `${where}: duplicate bioguide ${bg}`
    const last = r.terms[r.terms.length - 1]!
    members.set(bg, last.type === 'rep' ? [displayName(r.name), last.district as number] : [displayName(r.name)])
    if (last.type === 'sen') {
      const l = r.id.lis!
      if (lis.has(l)) return `${where}: duplicate lis ${l}`
      lis.set(l, bg)
    }
    return null
  }
  for (const [i, r] of (rows as LegislatorRecord[]).entries()) {
    const p = add(r, `current[${i}]`, false)
    if (p) return fail(p)
    if (r.terms[r.terms.length - 1]!.type === 'sen') senators += 1
  }
  if (senators < SENATORS_RANGE[0] || senators > SENATORS_RANGE[1]) return fail(`${senators} senators, outside ${SENATORS_RANGE.join('-')}`)
  // A departed member who is back on the current roster keeps the current record (skipKnown).
  for (const [i, r] of departed.members.entries()) {
    const p = add(r, `departed[${i}]`, true)
    if (p) return fail(p)
  }

  const kept: string[] = []
  if (previous && previous.congress === departed.congress) {
    for (const [bg, entry] of Object.entries(previous.members)) {
      if (!members.has(bg)) {
        members.set(bg, entry)
        kept.push(bg)
      }
    }
    for (const [l, bg] of Object.entries(previous.lis)) {
      const now = lis.get(l)
      if (now === undefined) lis.set(l, bg)
      else if (now !== bg) return fail(`lis ${l} was ${bg} in the previous map and is ${now} now`)
    }
  }

  return {
    ok: true,
    map: {
      congress: departed.congress,
      source: {
        url: current.url,
        sha256: sha256Hex(current.body),
        last_modified: current.headers['last-modified'] ?? null,
        built_at: opts.builtAt,
        departed_seed: { url: departed.url, sha256: departed.sha256, fetched_at: departed.fetched_at, count: departed.count },
      },
      kept_from_previous: kept.sort(),
      members: sortedRecord(members),
      lis: sortedRecord(lis),
    },
  }
}

/**
 * The departed-member seed from legislators-historical.json (13.5 MB, too big to commit): members whose last term ends
 * after `congressStart` (the first day of the Congress), trimmed to the fields buildMembersMap reads. Pure; fails closed
 * on a non-array body or a record that breaks the structural checks.
 */
export function extractDeparted(
  historical: unknown,
  meta: { url: string; sha256: string; fetched_at: string },
  congress: number,
  congressStart: string,
): { ok: true; seed: DepartedSeed } | { ok: false; error: string } {
  if (!Array.isArray(historical)) return { ok: false, error: 'historical body is not a JSON array' }
  const out: LegislatorRecord[] = []
  for (const [i, r] of (historical as LegislatorRecord[]).entries()) {
    const last = Array.isArray(r?.terms) ? r.terms[r.terms.length - 1] : undefined
    if (!last || typeof last.end !== 'string' || !(last.end > congressStart)) continue
    const p = recordProblem(r, `historical[${i}]`)
    if (p) return { ok: false, error: p }
    const name: LegislatorRecord['name'] = { last: r.name.last }
    for (const k of ['first', 'middle', 'nickname', 'suffix', 'official_full'] as const) if (typeof r.name[k] === 'string') name[k] = r.name[k]
    const term: LegislatorRecord['terms'][number] = { type: last.type, start: last.start, end: last.end, state: last.state }
    if (last.type === 'rep') term.district = last.district as number
    out.push({ id: last.type === 'sen' ? { bioguide: r.id.bioguide, lis: r.id.lis! } : { bioguide: r.id.bioguide }, name, terms: [term] })
  }
  out.sort((a, b) => (a.id.bioguide < b.id.bioguide ? -1 : a.id.bioguide > b.id.bioguide ? 1 : 0))
  return { ok: true, seed: { ...meta, congress, congress_start: congressStart, count: out.length, members: out } }
}

/** The committed text of a map: stable key order, one member / lis entry per line (small, reviewable diffs). */
export function serializeMembersMap(m: MembersMap): string {
  const line = (k: string, v: unknown) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`
  const block = (o: Record<string, unknown>) => {
    const ks = Object.keys(o)
    return ks.length === 0 ? '{}' : `{\n${ks.map((k) => line(k, o[k])).join(',\n')}\n  }`
  }
  return [
    '{',
    `  "congress": ${JSON.stringify(m.congress)},`,
    `  "source": ${JSON.stringify(m.source, null, 2).replace(/\n/g, '\n  ')},`,
    `  "kept_from_previous": ${JSON.stringify(m.kept_from_previous)},`,
    `  "members": ${block(m.members)},`,
    `  "lis": ${block(m.lis)}`,
    '}',
    '',
  ].join('\n')
}

export interface MemberEntry {
  bioguide: string
  /** The map's display name (official_full, or nickname/first + last + suffix). */
  name: string
  /** House district (0 = at-large or delegate); null for a senator. */
  district: number | null
}

/** What a member-vote record cites as the map it used (MemberVotesRecord.members_map). */
export interface MembersMapMeta { sha256: string; source_last_modified: string | null; built_at: string }

export interface MembersLookup {
  /** By bioguide (a House `name-id` IS the bioguide). null = not in the map: use the XML's own name, never drift. */
  lookupHouse(bioguide: string): MemberEntry | null
  /** By Senate LIS member id. null = unresolved: key `lis:{id}`, the XML's own name (DESIGN §2.2). */
  lookupSenate(lis: string): MemberEntry | null
  readonly meta: MembersMapMeta
}

export function makeLookup(map: MembersMap): MembersLookup {
  const byBioguide = new Map<string, MemberEntry>()
  for (const [bg, v] of Object.entries(map.members)) byBioguide.set(bg, { bioguide: bg, name: v[0], district: v.length > 1 ? (v[1] as number) : null })
  const byLis = new Map<string, MemberEntry>()
  for (const [l, bg] of Object.entries(map.lis)) {
    const e = byBioguide.get(bg)
    if (e) byLis.set(l, e)
  }
  const meta: MembersMapMeta = { sha256: map.source.sha256, source_last_modified: map.source.last_modified, built_at: map.source.built_at }
  return {
    lookupHouse: (bioguide) => byBioguide.get(bioguide) ?? null,
    lookupSenate: (l) => byLis.get(l) ?? null,
    meta,
  }
}

/** The committed map (generated/members.json). The vote adapters' default `members` option. */
export const MEMBERS_MAP: MembersMap = generated as unknown as MembersMap
export const MEMBERS: MembersLookup = makeLookup(MEMBERS_MAP)
export const lookupHouse = MEMBERS.lookupHouse
export const lookupSenate = MEMBERS.lookupSenate

/** The vote adapters' injectable options (DESIGN §2.2): `parseVote(endpointId, res, opts = DEFAULT_VOTE_OPTIONS)`. The
 * SourceDefinition's parse always uses the defaults; only the old-Congress goldens (vote_115_2_00223,
 * vote_117_1_00059, vote_116_2_00292) pass `{ members: MEMBERS, maxUnresolved: 100 }`, and each also runs once with the
 * defaults expecting drift. */
export interface ParseVoteOptions {
  members: MembersLookup
  /** More unresolved Senate positions than this in one vote = drift for the whole payload ("member list stale or
   * wrong"); 1..max = publish, labeled, counted in the health detail. House name misses never drift. */
  maxUnresolved: number
}
export const MAX_UNRESOLVED_DEFAULT = 5
export const DEFAULT_VOTE_OPTIONS: Readonly<ParseVoteOptions> = Object.freeze({ members: MEMBERS, maxUnresolved: MAX_UNRESOLVED_DEFAULT })
